/**
 * Build 021 — CLAUDE.md Generator (deterministic)
 *
 * Governance note (Article IX): No LLM is used here. This function is a pure,
 * inspectable mapping from validated form input to a CLAUDE.md scaffold. It never
 * infers project facts the user did not provide. Missing sections are rendered as
 * explicit `TODO:` markers, not invented content — "demonstrate, never claim."
 */

export type BuildType =
  | "web-app"
  | "automation"
  | "api-service"
  | "cli-tool"
  | "content-site"
  | "other";

export interface ClaudeMdInput {
  projectName: string;
  oneLiner: string;          // plain-english "what it is"
  buildType: BuildType;
  notes: string;             // loose notes / drafted copy — verbatim, never rewritten
  primaryGoal: string;       // what "done" looks like
  stack: string[];           // selected from a fixed list; free-text appended as-is
  constraints: string;       // known limits, non-goals
  email: string;
}

const nonEmpty = (s: string) => s.trim().length > 0;
const slug = (s: string) =>
  s.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "project";

/** Verbatim block — user's loose notes preserved as data, never paraphrased. */
function verbatimNotes(notes: string): string {
  if (!nonEmpty(notes)) return "> TODO: No notes were provided. Add context before starting.";
  // Preserve the user's exact words; only guard the fence.
  return notes.replace(/```/g, "``\u200b`");
}

function stackBlock(stack: string[]): string {
  const cleaned = stack.map((s) => s.trim()).filter(nonEmpty);
  if (cleaned.length === 0) return "- TODO: No stack selected. Confirm before scaffolding.";
  return cleaned.map((s) => `- ${s}`).join("\n");
}

function buildTypeGuidance(t: BuildType): string {
  switch (t) {
    case "web-app":
      return "This is a web application. Prefer the Baseline Stack (Next.js App Router, TypeScript, Tailwind, Vercel). Do NOT use `output: 'export'` if any live API route, auth, or database access is required.";
    case "automation":
      return "This is an automation build. n8n (cloud-hosted) is the orchestration layer. Prefer raw HTTP Request nodes over native service nodes for version stability. Use upsert-by-email for deduplication where applicable.";
    case "api-service":
      return "This is an API/service build. Define the request/response contract explicitly before writing handlers. Validate all input at the boundary.";
    case "cli-tool":
      return "This is a CLI tool. Keep commands composable and side-effect-explicit. Document every flag.";
    case "content-site":
      return "This is a content site. Static generation is acceptable here since there are no live API routes. Prioritize SEO, structured data, and performance.";
    default:
      return "TODO: Build type is 'other'. State the architecture assumptions explicitly before scaffolding.";
  }
}

export function generateClaudeMd(input: ClaudeMdInput): string {
  const s = slug(input.projectName);
  const name = nonEmpty(input.projectName) ? input.projectName.trim() : "TODO: Project Name";
  const oneLiner = nonEmpty(input.oneLiner) ? input.oneLiner.trim() : "TODO: One-line description.";
  const goal = nonEmpty(input.primaryGoal) ? input.primaryGoal.trim() : "TODO: Define what 'done' looks like.";
  const constraints = nonEmpty(input.constraints)
    ? input.constraints.trim()
    : "TODO: No constraints or non-goals stated. Confirm scope before building.";

  return `# CLAUDE.md

> Generated by IAS Build 021 — CLAUDE.md Generator.
> This file is a deterministic scaffold. Sections marked \`TODO:\` were not supplied
> and must be resolved before or during the first build session.

## Project

**${name}**

${oneLiner}

- **Slug:** \`${s}\`
- **Build type:** \`${input.buildType}\`

## Objective

${goal}

## Build-Type Guidance

${buildTypeGuidance(input.buildType)}

## Tech Stack

${stackBlock(input.stack)}

## Constraints & Non-Goals

${constraints}

## Source Notes (verbatim)

The following are the author's original notes, preserved without modification.
Treat these as the source of truth for intent. Where they conflict with this
scaffold's TODOs, the notes win.

\`\`\`
${verbatimNotes(input.notes)}
\`\`\`

## Working Agreement (for Claude Code)

- **Describe, review, accept.** Before writing files, restate what you're about to do. Wait for confirmation on structural decisions.
- **Demonstrate, never claim.** No fabricated data, metrics, or "it works" without a runnable path. Label all mock data as mock.
- **Surface gaps honestly.** When you hit an unresolved decision, name it as a \`TODO:\` in code rather than guessing.
- **Prefer simple over clever.** Avoid premature optimization and unnecessary dependencies.

## First Steps

1. Read this file in full.
2. Set up the project and folder structure.
3. Confirm the stack and resolve any \`TODO:\` markers with me before scaffolding features.
4. Then we build workflows together.

---
*Generated ${new Date().toISOString().slice(0, 10)} · IAS Build 021*
`;
}
